Repository 4l3x-suvnet/todo_calendar, pull requests merged in 2022-06, with the labels that each got.

#21 Header added
  index.html
Labels: requirement

#41 Add a new font family quicksand put in html global
  css/global.css
  index.html
Labels: design

#48 44 add images folder
  img/png-transparent-frog-umbrella-rain-tarui-ear-frog-child-food-leaf.png
Labels: design

#70 Highlight selected day in grid
  css/desktop.css
  js/calendar.js
Labels: design

#78 Add background to the calendar
  css/desktop.css
  img/calendar-background.png
Labels: design

#91 Todo items ID should be unique
  js/todos.js
Labels: bug
